import { useEffect, useState } from "react";
import * as catalogApi from "../api/catalogApi.js";
import { isRealApiEnabled } from "../api/config.js";
import { getSelectedMarketId } from "../api/authSession.js";
import { Button, Card, PageHeader, ProductThumbnail, StatusBadge, Table } from "../components/ui/index.js";

const blank = { private_name: "", private_brand_text: "", private_barcode: "", private_sku: "", private_package_size: "", private_package_type: "", regular_price: "", promo_price: "", currency: "EUR", badge_text: "", stock_note: "" };

export function MarketCatalog() {
  const [tab, setTab] = useState("mine"); const [query, setQuery] = useState("");
  const [mine, setMine] = useState([]); const [shared, setShared] = useState([]);
  const [form, setForm] = useState(blank); const [busy, setBusy] = useState(isRealApiEnabled); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const marketId = getSelectedMarketId();
  async function loadMine() { if (!isRealApiEnabled) return; setBusy(true); try { setMine((await catalogApi.listMyProducts({ limit: 200 }, marketId)).items || []); setError(""); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function loadShared() { if (!isRealApiEnabled) return; setBusy(true); try { setShared((await catalogApi.listSharedCatalog({ search: query || undefined, limit: 100 }, marketId)).items || []); setError(""); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  useEffect(() => { loadMine(); }, [marketId]); useEffect(() => { if (tab === "shared") loadShared(); }, [tab]);
  async function adopt(item) { try { await catalogApi.adoptSharedProduct(item.id, {}, marketId); setMessage("Ürün kataloğunuza eklendi."); await loadMine(); await loadShared(); } catch (e) { setError(e.message); } }
  async function createPrivate(event) { event.preventDefault(); try { await catalogApi.createPrivateProduct({ ...form, regular_price: form.regular_price === "" ? null : Number(form.regular_price), promo_price: form.promo_price === "" ? null : Number(form.promo_price) }, marketId); setForm(blank); setMessage("Özel ürün oluşturuldu."); setTab("mine"); await loadMine(); } catch (e) { setError(e.message); } }
  const products = tab === "mine" ? mine : shared;
  return <><PageHeader title="Ürünlerim" description="Paylaşılan ürünleri ekleyin veya kendi ürününüzü oluşturun." actions={<><Button variant={tab === "mine" ? "primary" : "secondary"} onClick={() => setTab("mine")}>Ürünlerim</Button><Button variant={tab === "shared" ? "primary" : "secondary"} onClick={() => setTab("shared")}>Paylaşılan Katalog</Button><Button onClick={() => setTab("private")}>Özel Ürün Oluştur</Button></>} />{error ? <p className="inline-result inline-result-warning">{error}</p> : null}{message ? <p className="inline-result">{message}</p> : null}{tab === "private" ? <Card title="Özel Ürün Oluştur"><form className="form-grid" onSubmit={createPrivate}>{Object.entries(form).map(([key, value]) => <label key={key}><span>{key.replaceAll("_", " ")}</span><input value={value} required={key === "private_name"} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<Button type="submit" variant="primary">Oluştur</Button></form></Card> : <Card title={tab === "mine" ? "Ürünlerim" : "Paylaşılan Katalog"}><div className="filter-bar"><input aria-label="Ürün ara" placeholder="Ürün, marka, barkod veya kategori ara" value={query} onChange={(e) => setQuery(e.target.value)} /><Button onClick={tab === "shared" ? loadShared : loadMine}>Ara</Button></div>{busy ? <p className="inline-result">Ürünler yükleniyor...</p> : null}<Table columns={tab === "mine" ? ["Görsel", "Ad", "Marka", "Kategori", "Normal", "Promosyon", "Durum", "Kaynak"] : ["Görsel", "Ad", "Marka", "Paket", "Kategori", "Durum", "Aksiyon"]}>{products.map((item) => <tr key={item.id}><td><ProductThumbnail label={item.name} hasImage={Boolean(item.image_url)} /></td><td>{item.name}</td><td>{item.brand || "-"}</td>{tab === "mine" ? <><td>{item.category || "-"}</td><td>{item.regular_price ?? "-"} {item.currency}</td><td>{item.promo_price ?? "-"}</td><td><StatusBadge status={item.is_active ? "Aktif" : "Pasif"} /></td><td>{item.source_type}</td></> : <><td>{[item.package_size, item.package_type].filter(Boolean).join(" · ") || "-"}</td><td>{item.category || "-"}</td><td><StatusBadge status={item.is_active ? "Aktif" : "Pasif"} /></td><td><Button disabled={!item.is_active || item.already_added} onClick={() => adopt(item)}>{item.already_added ? "Eklendi" : "Kataloğa ekle"}</Button></td></>}</tr>)}</Table>{!busy && products.length === 0 ? <p className="catalog-empty">Ürün bulunamadı.</p> : null}</Card>}</>;
}
