import { useEffect, useRef, useState } from "react";
import { canManageTemplates, getSelectedMarketId } from "../api/authSession.js";
import { isRealApiEnabled } from "../api/config.js";
import { templates as mockTemplates } from "../data/mockData.js";
import { getTemplates } from "../data/dataSource.js";
import { adoptTemplate, createCustomTemplate, getMyTemplates, getSharedTemplates, getTemplatePresets, setDefaultTemplate, updateTemplate, uploadTemplateThumbnail } from "../api/templateApi.js";
import { Badge, Button, Modal, PageHeader, TemplateThumbnail } from "../components/ui/index.js";
import { TemplateBuilderModal } from "../components/templates/TemplateBuilderModal.jsx";

const fallbackPresets = { items: [], page_formats: [{ value: "a4_portrait", label: "A4 dikey" }], price_styles: ["bold"], badge_styles: ["pill"], header_styles: ["burst"], card_styles: ["shadow"], image_treatments: ["stage"] };
const range = (template) => `${template.ideal_product_min || Math.max(1, Number(template.config_json?.slot_count || 4) - 4)}–${template.ideal_product_max || template.config_json?.slot_count || 16} ürün`;
const description = (template) => template.user_description || template.description || "Kampanyalarınız için uyarlanabilir tasarım.";
const format = (template) => template.config_json?.page_format === "a4_landscape" ? "A4 • Yatay" : "A4 • Dikey";

function TemplateCard({ template, marketId, added, recommended, mine, canManage, onPreview, onUse, onEdit, onToggle, onDefault }) {
  return <article className="card template-real-card gallery-template-card">
    <button type="button" className="template-thumb-link" onClick={() => onPreview(template)} aria-label={`${template.name} önizlemesini aç`}><TemplateThumbnail templateId={template.id} marketId={marketId} name={template.name} realPreview /></button>
    <div className="gallery-card-head">{recommended ? <Badge tone="primary">Önerilen</Badge> : null}{template.isDefault ? <Badge>Varsayılan</Badge> : null}{added ? <Badge tone="success">Şablonlarınıza eklendi</Badge> : null}</div>
    <h3>{template.name}</h3><p>{description(template)}</p><small><strong>İdeal: {range(template)}</strong> · {format(template)}</small>
    <div className="table-actions"><Button onClick={() => onPreview(template)}>Önizle</Button><Button variant="primary" onClick={() => onUse(template)} disabled={added && !mine}>{added && !mine ? "Şablonlarınıza eklendi" : "Bu şablonu kullan"}</Button>{mine && canManage ? <details className="template-overflow"><summary aria-label={`${template.name} yönetim menüsü`}>⋯</summary><div><button type="button" onClick={() => onEdit(template)}>Düzenle</button><button type="button" onClick={() => onDefault(template)}>Varsayılan yap</button><button type="button" onClick={() => onToggle(template)}>{template.is_active ? "Pasifleştir" : "Aktifleştir"}</button></div></details> : null}</div>
  </article>;
}

export function Templates() {
  const marketId = getSelectedMarketId(); const canManage = canManageTemplates(); const savingRef = useRef(false);
  const [shared, setShared] = useState([]); const [mine, setMine] = useState([]); const [adoptedIds, setAdoptedIds] = useState([]); const [presets, setPresets] = useState(fallbackPresets); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [preview, setPreview] = useState(null); const [builder, setBuilder] = useState(undefined); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { if (!isRealApiEnabled) { setShared(mockTemplates); setMine([]); return; } const [globalResult, mineResult, presetResult] = await Promise.all([getSharedTemplates(marketId), getMyTemplates(marketId), getTemplatePresets(marketId)]); setShared(globalResult.items || []); setAdoptedIds((mineResult.items || []).filter((item) => item.source_template_id).map((item) => String(item.source_template_id))); setMine((mineResult.items || []).filter((item) => !item.source_template_id)); setPresets(presetResult || fallbackPresets); } catch (error) { setMessage(error.message || "Şablonlar yüklenemedi."); } };
  useEffect(() => { load(); }, [marketId]);
  const adopted = new Set(adoptedIds);
  const matches = (template) => { const text = `${template.name} ${description(template)} ${template.display_category || ""}`.toLocaleLowerCase("tr-TR"); if (query && !text.includes(query.toLocaleLowerCase("tr-TR"))) return false; const max = template.ideal_product_max || Number(template.config_json?.slot_count || 16); const min = template.ideal_product_min || Math.max(1, max - 4); return filter === "all" || (filter === "small" && min <= 4) || (filter === "medium" && max >= 5 && min <= 9) || (filter === "large" && max >= 10) || (filter === "premium" && (template.display_category === "Premium" || template.slug === "premium-market")); };
  const ready = shared.filter(matches); const custom = mine.filter(matches); const contextCount = filter === "small" ? 4 : filter === "medium" ? 9 : filter === "large" ? 16 : null; const recommended = [...ready, ...custom].sort((a, b) => Math.abs((((a.ideal_product_min || 1) + (a.ideal_product_max || 16)) / 2) - (contextCount || 8)) - Math.abs((((b.ideal_product_min || 1) + (b.ideal_product_max || 16)) / 2) - (contextCount || 8)))[0];
  const useTemplate = async (template) => { if (!isRealApiEnabled) { setMessage(`${template.name} yeni kampanyada seçilebilir.`); return; } if (template.is_global) { try { setBusy(true); await adoptTemplate(template.id, marketId); setMessage(`${template.name} şablonlarınıza eklendi.`); await load(); } catch (error) { setMessage(error.status === 409 ? "Bu şablon zaten şablonlarınıza eklendi." : error.message); } finally { setBusy(false); } } else { window.location.hash = "#/campaigns/new"; } };
  const saveBuilder = async (form) => { if (savingRef.current) return; savingRef.current = true; try { setBusy(true); const { thumbnail, ...payload } = form; const saved = builder ? await updateTemplate(builder.id, payload, marketId) : await createCustomTemplate(payload, marketId); if (thumbnail) await uploadTemplateThumbnail(saved.id, thumbnail, marketId); setBuilder(undefined); await load(); } catch (error) { setMessage(error.message || "Şablon kaydedilemedi."); } finally { savingRef.current = false; setBusy(false); } };
  return <><PageHeader title="Şablonlar" description="Kampanyanız için uygun tasarımı seçin. Ürün sayınıza göre en uygun şablonları gösterebiliriz." actions={canManage ? <Button variant="primary" onClick={() => setBuilder(null)}>+ Özel şablon oluştur</Button> : null} />
    {message ? <p className="inline-result">{message}</p> : null}<div className="gallery-controls"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Şablon ara" aria-label="Şablon ara" />{[["all", "Tümü"], ["small", "1–4 ürün"], ["medium", "5–9 ürün"], ["large", "10+ ürün"], ["premium", "Premium"]].map(([value, label]) => <button type="button" className={filter === value ? "is-selected" : ""} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div>
    {recommended ? <section className="template-section"><h2>Önerilen</h2><div className="template-management-grid"><TemplateCard template={recommended} marketId={marketId} recommended canManage={canManage} onPreview={setPreview} onUse={useTemplate} added={false} /></div></section> : null}
    <section className="template-section"><h2>Hazır Şablonlar</h2><p>LeafletPilot tarafından hazırlanmış kullanıma hazır tasarımlar.</p><div className="template-management-grid">{ready.map((template) => <TemplateCard key={template.id} template={template} marketId={marketId} added={adopted.has(String(template.id))} canManage={canManage} onPreview={setPreview} onUse={useTemplate} />)}</div></section>
    <section className="template-section"><h2>Şablonlarım</h2><div className="template-management-grid">{custom.length ? custom.map((template) => <TemplateCard key={template.id} template={template} marketId={marketId} mine canManage={canManage} onPreview={setPreview} onUse={useTemplate} onEdit={setBuilder} onDefault={async (template) => { await setDefaultTemplate(template.id, marketId); await load(); }} onToggle={async (template) => { await updateTemplate(template.id, { is_active: !template.is_active }, marketId); await load(); }} />) : <p className="catalog-empty">Henüz size özel bir şablon yok.</p>}</div></section>
    {preview ? <Modal title={preview.name} description={description(preview)} onClose={() => setPreview(null)} footer={<Button variant="primary" onClick={() => useTemplate(preview)} disabled={busy}>Bu şablonu kullan</Button>}><div className="template-preview-modal"><TemplateThumbnail templateId={preview.id} marketId={marketId} name={preview.name} realPreview /><p><strong>İdeal: {range(preview)}</strong><br />{format(preview)} · {preview.display_category || "Dengeli"}</p></div></Modal> : null}
    {builder !== undefined ? <TemplateBuilderModal template={builder} presets={presets} busy={busy} error={message} onClose={() => setBuilder(undefined)} onSave={saveBuilder} /> : null}
  </>;
}