import { useState } from "react";
import { platformApi } from "../../api/platformApi.js";
import { Modal } from "../../components/ui/Modal.jsx";

const labels = { new: "Yeni", update: "Güncellenecek", unchanged: "Değişiklik yok", invalid: "Geçersiz", ambiguous: "Belirsiz", conflict: "Çakışma" };
const errorText = (error) => error?.body?.detail || error?.message || "İşlem tamamlanamadı.";

export function PlatformProductImportModal({ onClose, onImported }) {
  const [file, setFile] = useState(null); const [imagesZip, setImagesZip] = useState(null); const [preview, setPreview] = useState(null); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const choose = (event) => { const next = event.target.files?.[0]; if (!next) return; if (!next.name.toLowerCase().endsWith(".xlsx")) { setError("Lütfen .xlsx dosyası seçin."); return; } if (next.size > 10 * 1024 * 1024) { setError("Excel dosyası en fazla 10 MiB olabilir."); return; } setFile(next); setPreview(null); setResult(null); setError(""); };
  const analyze = async () => { if (!file) return; setBusy(true); setError(""); try { setPreview(await platformApi.previewGlobalProductImport(file, imagesZip)); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const confirm = async () => { if (!file) return; setBusy(true); setError(""); try { const next = await platformApi.importGlobalProducts(file, imagesZip); setResult(next); onImported?.(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const summary = preview?.counts;
  return <Modal title="Excel ile Ürün Yükle" description="Önce dosyayı doğrulayın; geçersiz veya çakışan satırlar aktarılmaz." onClose={onClose}>
    <div className="form-grid"><label>Ürün Excel dosyası<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={choose} /></label><label>Görseller ZIP dosyası <small>(isteğe bağlı; görseller/ altında eşleşen dosyalar)</small><input type="file" accept=".zip,application/zip" onChange={(event) => { const next = event.target.files?.[0]; if (next && !next.name.toLowerCase().endsWith(".zip")) setError("Lütfen .zip dosyası seçin."); else setImagesZip(next || null); }} /></label>{error && <p className="error-message" role="alert">{error}</p>}
      {!preview && !result && <div className="page-actions"><button type="button" onClick={analyze} disabled={!file || busy}>{busy ? "Kontrol ediliyor..." : "Önizleme oluştur"}</button><button type="button" onClick={onClose}>İptal</button></div>}
      {summary && !result && <><div className="catalog-import-summary"><span>Toplam {summary.total}</span><span>Yeni {summary.new}</span><span>Güncellenecek {summary.update}</span><span>Hatalı {summary.invalid}</span><span>Çakışan {summary.conflict + summary.ambiguous}</span><span>Görselli {summary.with_image}</span><span>Görsel dosyası eksik {summary.images_missing}</span><span>Geçersiz görsel {summary.images_invalid}</span></div><div className="catalog-import-table"><table><thead><tr><th>Satır</th><th>Ürün</th><th>Marka</th><th>Kategori</th><th>Görsel</th><th>İşlem</th><th>Uyarı</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.row}><td>{row.row}</td><td>{row.canonical_name}</td><td>{row.brand}</td><td>{row.category}</td><td>{row.image_filename || "-"}{row.image_status === "missing" ? " · Eksik" : row.image_status === "ready" ? " · Hazır" : row.image_status === "invalid" ? " · Geçersiz" : ""}</td><td>{labels[row.status] || row.status}</td><td>{row.error || "-"}</td></tr>)}</tbody></table></div><div className="page-actions"><button type="button" onClick={confirm} disabled={busy}>{busy ? "Aktarılıyor..." : "Geçerli satırları aktar"}</button><button type="button" onClick={onClose} disabled={busy}>İptal</button></div></>}
      {result && <><p className="success-message" role="status">{result.created} ürün oluşturuldu, {result.updated} ürün güncellendi, {result.unchanged} ürün değişmedi; {result.skipped} satır atlandı. {result.images_uploaded} görsel yüklendi, {result.images_missing} görsel eksik, {result.images_invalid} görsel geçersiz; {result.images_awaiting_review} görsel inceleme bekliyor.</p><button type="button" onClick={onClose}>Tamam</button></>}
    </div>
  </Modal>;
}
